import {
  UserProfile,
  Trip,
  DestinationCity,
  ActivityItem,
  CommunityPost,
  AdminStats,
  AdminUser,
} from "./types";

export const initialUser: UserProfile = {
  id: "usr-01",
  firstName: "Aarav",
  lastName: "Shah",
  email: "aarav.travels@globetrotter.io",
  phone: "+91 98765 43210",
  city: "Ahmedabad",
  country: "India",
  bio: "Architect & nomad photographer. Passionate about alpine hikes, historical castles, and discovering hidden ramen bars.",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
  role: "traveler",
  language: "English (US)",
  currency: "USD ($)",
  travelStyle: ["Adventure", "Photography", "Cultural Immersion", "Budget Smart"],
  totalTrips: 12,
  countriesVisited: 18,
  totalSavings: 1420,
};

export const sampleCities: DestinationCity[] = [
  {
    id: "city-paris",
    name: "Paris",
    country: "France",
    region: "Europe",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop&q=80",
    tagline: "The City of Light, art galleries, and romantic boulevards",
    costIndex: "$$$",
    popularityScore: 98,
    avgDailyCost: 185,
    bestSeason: "Apr - Oct",
    activitiesCount: 42,
  },
  {
    id: "city-tokyo",
    name: "Tokyo",
    country: "Japan",
    region: "Asia",
    image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&auto=format&fit=crop&q=80",
    tagline: "Futuristic neon metropolises meet ancient tranquil shrines",
    costIndex: "$$$",
    popularityScore: 99,
    avgDailyCost: 170,
    bestSeason: "Mar - May, Sep - Nov",
    activitiesCount: 56,
  },
  {
    id: "city-nyc",
    name: "New York City",
    country: "United States",
    region: "Americas",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&auto=format&fit=crop&q=80",
    tagline: "The city that never sleeps, Broadway, and iconic skyline views",
    costIndex: "$$$$",
    popularityScore: 96,
    avgDailyCost: 240,
    bestSeason: "May - Oct",
    activitiesCount: 65,
  },
  {
    id: "city-interlaken",
    name: "Interlaken & Swiss Alps",
    country: "Switzerland",
    region: "Europe",
    image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&auto=format&fit=crop&q=80",
    tagline: "Glacial lakes, soaring snow peaks, and paragliding havens",
    costIndex: "$$$$",
    popularityScore: 94,
    avgDailyCost: 220,
    bestSeason: "Dec - Mar (Ski), Jun - Sep (Hikes)",
    activitiesCount: 28,
  },
  {
    id: "city-bali",
    name: "Bali & Ubud",
    country: "Indonesia",
    region: "Asia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=80",
    tagline: "Lush terraced paddies, sacred water temples, and coral reefs",
    costIndex: "$",
    popularityScore: 95,
    avgDailyCost: 65,
    bestSeason: "May - Sep",
    activitiesCount: 38,
  },
  {
    id: "city-capetown",
    name: "Cape Town",
    country: "South Africa",
    region: "Africa",
    image: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800&auto=format&fit=crop&q=80",
    tagline: "Dramatic Table Mountain vistas, coastal vineyards, and penguin colonies",
    costIndex: "$$",
    popularityScore: 91,
    avgDailyCost: 95,
    bestSeason: "Nov - Mar",
    activitiesCount: 31,
  },
];

export const sampleActivities: ActivityItem[] = [
  {
    id: "act-paraglide-alps",
    name: "Tandem Paragliding over Jungfrau Alps",
    city: "Interlaken & Swiss Alps",
    country: "Switzerland",
    category: "Adventure",
    cost: 190,
    durationHours: 3,
    rating: 4.95,
    reviewsCount: 340,
    image: "https://images.unsplash.com/photo-1527004013197-933c4bb611b3?w=800&auto=format&fit=crop&q=80",
    description: "Launch off 1,300m cliffs and glide over shimmering turquoise lakes with certified alpine tandem pilots.",
    location: "Beatenberg Launch Base, Interlaken",
    tag: "High Adrenaline",
    bestTime: "Morning 09:00 AM",
  },
  {
    id: "act-louvre-tour",
    name: "Louvre Museum After-Hours VIP Access",
    city: "Paris",
    country: "France",
    category: "Culture",
    cost: 85,
    durationHours: 3.5,
    rating: 4.88,
    reviewsCount: 890,
    image: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&auto=format&fit=crop&q=80",
    description: "Skip massive crowds to view the Mona Lisa, Venus de Milo, and French Crown Jewels with an art historian.",
    location: "Rue de Rivoli, 75001 Paris",
    tag: "Must-See Iconic",
    bestTime: "Evening 06:30 PM",
  },
  {
    id: "act-tokyo-food",
    name: "Shibuya & Shinjuku Midnight Street Food Crawl",
    city: "Tokyo",
    country: "Japan",
    category: "Culinary",
    cost: 75,
    durationHours: 3,
    rating: 4.92,
    reviewsCount: 520,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80",
    description: "Sample savory yakitori skewers, authentic tonkotsu ramen, match ice desserts, and local craft sake in Omoide Yokocho.",
    location: "Shinjuku West Gate, Tokyo",
    tag: "Foodie Choice",
    bestTime: "Night 07:30 PM",
  },
  {
    id: "act-nyc-broadway",
    name: "Broadway Orchestra Experience & Backstage Pass",
    city: "New York City",
    country: "United States",
    category: "Culture",
    cost: 160,
    durationHours: 3,
    rating: 4.9,
    reviewsCount: 410,
    image: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=800&auto=format&fit=crop&q=80",
    description: "Premium center orchestra seats for critically acclaimed stage productions followed by an exclusive backstage meet.",
    location: "Times Square Theatre District, NYC",
    tag: "Exclusive",
    bestTime: "Evening 08:00 PM",
  },
  {
    id: "act-bali-scuba",
    name: "Manta Point Scuba Diving & Nusa Penida Cruise",
    city: "Bali & Ubud",
    country: "Indonesia",
    category: "Adventure",
    cost: 110,
    durationHours: 6,
    rating: 4.97,
    reviewsCount: 680,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80",
    description: "Swim side-by-side with majestic giant oceanic manta rays and explore vibrant coral reefs in crystal clear waters.",
    location: "Sanur Harbor Speedboat Terminal",
    tag: "Marine Adventure",
    bestTime: "Morning 07:00 AM",
  },
  {
    id: "act-capetown-safari",
    name: "Aquila Big 5 Luxury Game Reserve Safari",
    city: "Cape Town",
    country: "South Africa",
    category: "Nature",
    cost: 155,
    durationHours: 8,
    rating: 4.91,
    reviewsCount: 310,
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&auto=format&fit=crop&q=80",
    description: "Open 4x4 safari expedition tracking lions, rhinos, elephants, buffalos, and leopards in the Karoo valley.",
    location: "Touws River, Western Cape",
    tag: "Bucket List",
    bestTime: "Full Day 06:30 AM",
  },
  {
    id: "act-eiffel-dinner",
    name: "Seine River Luxury Dinner Cruise & Eiffel Tower Lights",
    city: "Paris",
    country: "France",
    category: "Culinary",
    cost: 130,
    durationHours: 2.5,
    rating: 4.86,
    reviewsCount: 750,
    image: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&auto=format&fit=crop&q=80",
    description: "Three-course gourmet French dining while floating under illuminated historic Parisian stone bridges.",
    location: "Port de la Bourdonnais, Paris",
    tag: "Romantic",
    bestTime: "Evening 08:30 PM",
  },
  {
    id: "act-mount-fuji-tour",
    name: "Mount Fuji 5th Station & Lake Kawaguchiko Onsen",
    city: "Tokyo",
    country: "Japan",
    category: "Sightseeing",
    cost: 120,
    durationHours: 9,
    rating: 4.89,
    reviewsCount: 620,
    image: "https://images.unsplash.com/photo-1578637387939-43c525550085?w=800&auto=format&fit=crop&q=80",
    description: "Scenic coach tour to Mt. Fuji with traditional hot spring onsen bath and matcha tea tasting ceremony.",
    location: "Shinjuku Center Station, Tokyo",
    tag: "Day Trip",
    bestTime: "Full Day 08:00 AM",
  },
];

export const sampleTrips: Trip[] = [
  {
    id: "trip-paris-01",
    title: "Paris Art & Gastronomy Dream",
    destination: "Paris",
    country: "France",
    coverImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop&q=80",
    startDate: "2024-01-09",
    endDate: "2024-01-14",
    durationDays: 6,
    description: "Immersive 6-day cultural escape exploring classical art museums, Montmartre artists, Michelin patisseries, and romantic Seine cruises.",
    status: "ongoing",
    estimatedBudget: 2200,
    actualExpense: 1845,
    sections: [
      {
        id: "sec-p1",
        title: "Flight & Transit Logistics",
        type: "travel",
        description: "Direct flight Air France AF218 + Paris Visite 5-day Metro passes",
        startDate: "2024-01-09",
        endDate: "2024-01-09",
        budget: 700,
        actualCost: 650,
        destinationCity: "Paris",
      },
      {
        id: "sec-p2",
        title: "Le Marais Boutique Stay",
        type: "stay",
        description: "5 Nights at Hotel Fabric, historical heritage textile factory conversion",
        startDate: "2024-01-09",
        endDate: "2024-01-14",
        budget: 950,
        actualCost: 820,
        destinationCity: "Paris",
      },
      {
        id: "sec-p3",
        title: "Louvre, Musée d'Orsay & Seine Dining",
        type: "activity",
        description: "VIP Museum passes, private Louvre guide, and Seine sunset dinner cruise",
        startDate: "2024-01-10",
        endDate: "2024-01-13",
        budget: 550,
        actualCost: 375,
        destinationCity: "Paris",
      },
    ],
    days: [
      {
        dayNumber: 1,
        date: "2024-01-09",
        city: "Paris",
        totalDayExpense: 340,
        activities: [
          {
            id: "d1-a1",
            timeSlot: "10:30 AM",
            title: "Check-in at Le Marais Boutique Hotel",
            description: "Unpack, refresh with welcome espresso and French croissants.",
            location: "Rue de la Folie Méricourt, Paris",
            category: "Lodging",
            cost: 0,
            duration: "1.5h",
            completed: true,
          },
          {
            id: "d1-a2",
            timeSlot: "02:00 PM",
            title: "Stroll through Place des Vosges & Victor Hugo House",
            description: "Explore the oldest planned square in Paris and quaint antique bookstores.",
            location: "Place des Vosges, 75004 Paris",
            category: "Sightseeing",
            cost: 25,
            duration: "2.5h",
            completed: true,
          },
          {
            id: "d1-a3",
            timeSlot: "07:30 PM",
            title: "Welcome Dinner at Bistrot Paul Bert",
            description: "Traditional steak frites, soufflé, and Bordeaux wine pairing.",
            location: "18 Rue Paul Bert, 75011 Paris",
            category: "Culinary",
            cost: 95,
            duration: "2h",
            completed: true,
          },
        ],
      },
      {
        dayNumber: 2,
        date: "2024-01-10",
        city: "Paris",
        totalDayExpense: 260,
        activities: [
          {
            id: "d2-a1",
            timeSlot: "09:00 AM",
            title: "Louvre Museum After-Hours VIP Tour",
            description: "Viewing Mona Lisa, Winged Victory of Samothrace, and Apollo Gallery.",
            location: "Rue de Rivoli, Paris",
            category: "Culture",
            cost: 85,
            duration: "3.5h",
            completed: false,
          },
          {
            id: "d2-a2",
            timeSlot: "01:30 PM",
            title: "Tuileries Gardens & Angelina Hot Chocolate",
            description: "Iconic thick African hot chocolate and Mont-Blanc pastry.",
            location: "226 Rue de Rivoli, Paris",
            category: "Culinary",
            cost: 35,
            duration: "1.5h",
            completed: false,
          },
          {
            id: "d2-a3",
            timeSlot: "08:30 PM",
            title: "Seine River Luxury Dinner Cruise",
            description: "Panoramic glass boat with live jazz band and illuminated Eiffel views.",
            location: "Port de la Bourdonnais, Paris",
            category: "Culinary",
            cost: 140,
            duration: "2.5h",
            completed: false,
          },
        ],
      },
    ],
    expenseBreakdown: {
      transport: 650,
      stay: 820,
      activities: 245,
      meals: 130,
      miscellaneous: 0,
    },
    isPublic: true,
    sharesCount: 148,
    likesCount: 382,
    tags: ["Culture", "Art", "Romantic", "Europe"],
    companionAvatars: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    ],
  },
  {
    id: "trip-nyc-02",
    title: "NYC Autumn Skyline & Broadway Getaway",
    destination: "New York City",
    country: "United States",
    coverImage: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&auto=format&fit=crop&q=80",
    startDate: "2024-01-15",
    endDate: "2024-01-22",
    durationDays: 8,
    description: "8-day exploration of Manhattan rooftops, Central Park fall foliage, Chelsea Market gourmet food halls, and top Broadway theatre shows.",
    status: "upcoming",
    estimatedBudget: 3100,
    actualExpense: 2950,
    sections: [
      {
        id: "sec-n1",
        title: "Flights & Airport Transfers",
        type: "travel",
        description: "Roundtrip tickets + JFK Express train passes",
        startDate: "2024-01-15",
        endDate: "2024-01-15",
        budget: 900,
        actualCost: 880,
        destinationCity: "New York City",
      },
      {
        id: "sec-n2",
        title: "Arlo Midtown Manhattan Hotel",
        type: "stay",
        description: "7 nights corner king room near Hudson Yards",
        startDate: "2024-01-15",
        endDate: "2024-01-22",
        budget: 1500,
        actualCost: 1420,
        destinationCity: "New York City",
      },
      {
        id: "sec-n3",
        title: "Broadway, Summit One Vanderbilt & High Line",
        type: "activity",
        description: "Hamilton Broadway tickets, Summit observation deck, and MoMA passes",
        startDate: "2024-01-16",
        endDate: "2024-01-21",
        budget: 700,
        actualCost: 650,
        destinationCity: "New York City",
      },
    ],
    days: [
      {
        dayNumber: 1,
        date: "2024-01-15",
        city: "New York City",
        totalDayExpense: 180,
        activities: [
          {
            id: "dn1-1",
            timeSlot: "03:00 PM",
            title: "Check-in at Arlo Midtown",
            description: "Settle into rooftop terrace and take in Midtown skyline.",
            location: "351 W 38th St, New York",
            category: "Lodging",
            cost: 0,
            duration: "1h",
          },
          {
            id: "dn1-2",
            timeSlot: "06:00 PM",
            title: "Sunset Walk along High Line to Little Island",
            description: "Elevated park walk with autumn breeze and Hudson River views.",
            location: "The High Line, NYC",
            category: "Sightseeing",
            cost: 0,
            duration: "2h",
          },
          {
            id: "dn1-3",
            timeSlot: "08:30 PM",
            title: "Chelsea Market Tacos & Lobster Roll",
            description: "Casual dining at Los Tacos No.1 and Lobster Place.",
            location: "75 9th Ave, NYC",
            category: "Culinary",
            cost: 45,
            duration: "1.5h",
          },
        ],
      },
    ],
    expenseBreakdown: {
      transport: 880,
      stay: 1420,
      activities: 450,
      meals: 200,
      miscellaneous: 0,
    },
    isPublic: true,
    sharesCount: 92,
    likesCount: 245,
    tags: ["Skyline", "Broadway", "Nightlife", "Americas"],
    companionAvatars: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    ],
  },
  {
    id: "trip-japan-03",
    title: "Japan Winter Wonders & Alpine Onsens",
    destination: "Tokyo",
    country: "Japan",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&auto=format&fit=crop&q=80",
    startDate: "2024-01-16",
    endDate: "2024-01-23",
    durationDays: 8,
    description: "Magical 8-day journey through Tokyo's cyber districts, snow-capped Mount Fuji, Kyoto bamboo groves, and authentic cedar wood onsens.",
    status: "upcoming",
    estimatedBudget: 2800,
    actualExpense: 2650,
    sections: [
      {
        id: "sec-j1",
        title: "JR Pass & Shinkansen Bullet Train",
        type: "travel",
        description: "7-day Unlimited Green Car Shinkansen bullet train pass",
        startDate: "2024-01-16",
        endDate: "2024-01-23",
        budget: 450,
        actualCost: 420,
        destinationCity: "Tokyo",
      },
      {
        id: "sec-j2",
        title: "Ryokan with Private Hot Spring",
        type: "stay",
        description: "Authentic tatami mat stay in Hakone with mountain views",
        startDate: "2024-01-17",
        endDate: "2024-01-20",
        budget: 1200,
        actualCost: 1100,
        destinationCity: "Hakone / Tokyo",
      },
    ],
    days: [],
    expenseBreakdown: {
      transport: 420,
      stay: 1100,
      activities: 680,
      meals: 450,
      miscellaneous: 0,
    },
    isPublic: true,
    sharesCount: 310,
    likesCount: 640,
    tags: ["Snow", "Onsen", "Culture", "Asia"],
    companionAvatars: [],
  },
  {
    id: "trip-bali-04",
    title: "Bali Tropical Serenity & Scuba Trek",
    destination: "Bali & Ubud",
    country: "Indonesia",
    coverImage: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=80",
    startDate: "2023-11-04",
    endDate: "2023-11-12",
    durationDays: 9,
    description: "Rejuvenating wellness retreat with jungle infinity pools, Tegallalang rice terrace hikes, manta ray scuba diving, and volcanic sunrise summits.",
    status: "completed",
    estimatedBudget: 1400,
    actualExpense: 1290,
    sections: [
      {
        id: "sec-b1",
        title: "Villa Maya Ubud Jungle Sanctuary",
        type: "stay",
        description: "8 Nights in a private bamboo eco villa overlooking the sacred Ayung river",
        startDate: "2023-11-04",
        endDate: "2023-11-12",
        budget: 650,
        actualCost: 610,
        destinationCity: "Bali & Ubud",
      },
      {
        id: "sec-b2",
        title: "Manta Point Diving & Mount Batur Sunrise",
        type: "activity",
        description: "Scuba dive package + 4 AM volcanic sunrise trek with breakfast cooked on volcanic steam",
        startDate: "2023-11-06",
        endDate: "2023-11-10",
        budget: 380,
        actualCost: 350,
        destinationCity: "Bali & Ubud",
      },
    ],
    days: [],
    expenseBreakdown: {
      transport: 280,
      stay: 610,
      activities: 350,
      meals: 50,
      miscellaneous: 0,
    },
    isPublic: true,
    sharesCount: 420,
    likesCount: 910,
    tags: ["Tropical", "Scuba", "Wellness", "Asia"],
    companionAvatars: [
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    ],
  },
];

export const sampleCommunityPosts: CommunityPost[] = [
  {
    id: "post-01",
    author: {
      name: "Elena Rostova",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
      location: "Zürich, Switzerland",
      verified: true,
    },
    tripTitle: "10-Day Ultimate Swiss Alps & Glaciers Expedition",
    destination: "Interlaken & Swiss Alps",
    coverImage: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&auto=format&fit=crop&q=80",
    summary: "From thrilling tandem paragliding above Interlaken to riding the cogwheel train up to Jungfraujoch 'Top of Europe'. Every single frank spent was worth the panorama!",
    daysDuration: 10,
    budgetTotal: 2450,
    likes: 842,
    likedByMe: false,
    commentsCount: 94,
    sharesCount: 178,
    tags: ["SwissAlps", "Paragliding", "Glaciers", "Trekking"],
    createdAt: "2 hours ago",
    clonedCount: 142,
    tripData: {
      title: "10-Day Swiss Alps Grand Tour",
      destination: "Interlaken & Swiss Alps",
      country: "Switzerland",
      estimatedBudget: 2450,
      durationDays: 10,
    },
  },
  {
    id: "post-02",
    author: {
      name: "Kenji Takahashi",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
      location: "Kyoto, Japan",
      verified: true,
    },
    tripTitle: "Hidden Izakayas & Cyberpunk Tokyo Guide",
    destination: "Tokyo",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&auto=format&fit=crop&q=80",
    summary: "Skip the tourist traps! Here is my curated 7-day secret itinerary of tiny 4-seat alley izakayas, retro arcade halls in Akihabara, and peaceful dawn shrine rituals.",
    daysDuration: 7,
    budgetTotal: 1650,
    likes: 1240,
    likedByMe: true,
    commentsCount: 165,
    sharesCount: 380,
    tags: ["TokyoSecret", "Foodie", "Nightlife", "Cyberpunk"],
    createdAt: "1 day ago",
    clonedCount: 318,
    tripData: {
      title: "Hidden Izakayas & Cyberpunk Tokyo",
      destination: "Tokyo",
      country: "Japan",
      estimatedBudget: 1650,
      durationDays: 7,
    },
  },
  {
    id: "post-03",
    author: {
      name: "Camille Laurent",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80",
      location: "Lyon, France",
      verified: true,
    },
    tripTitle: "Parisian Micro-Bakeries & Classical Museums Circuit",
    destination: "Paris",
    coverImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop&q=80",
    summary: "A romantic lover's guide to finding warm sourdough baguettes, hidden courtyard art studios, and avoiding long museum ticket queues.",
    daysDuration: 5,
    budgetTotal: 1350,
    likes: 670,
    likedByMe: false,
    commentsCount: 48,
    sharesCount: 112,
    tags: ["ParisGuide", "BakeryLovers", "Architecture", "Art"],
    createdAt: "3 days ago",
    clonedCount: 95,
    tripData: {
      title: "Parisian Micro-Bakeries & Art",
      destination: "Paris",
      country: "France",
      estimatedBudget: 1350,
      durationDays: 5,
    },
  },
];

export const sampleAdminUsers: AdminUser[] = [
  {
    id: "adm-u1",
    name: "Aarav Shah",
    email: "aarav.travels@globetrotter.io",
    role: "Traveler",
    status: "Active",
    joinDate: "Jan 12, 2023",
    tripsCount: 12,
    spentTotal: 18450,
  },
  {
    id: "adm-u2",
    name: "Elena Rostova",
    email: "elena.r@alpinevoyages.ch",
    role: "Moderator",
    status: "Active",
    joinDate: "Mar 05, 2023",
    tripsCount: 19,
    spentTotal: 34200,
  },
  {
    id: "adm-u3",
    name: "Kenji Takahashi",
    email: "kenji.t@tokyoneon.jp",
    role: "Traveler",
    status: "Active",
    joinDate: "Jun 18, 2023",
    tripsCount: 8,
    spentTotal: 14800,
  },
  {
    id: "adm-u4",
    name: "Sarah Jenkins",
    email: "sarah.j@wanderlust.com",
    role: "Traveler",
    status: "Inactive",
    joinDate: "Sep 22, 2023",
    tripsCount: 3,
    spentTotal: 4900,
  },
  {
    id: "adm-u5",
    name: "Admin Superuser",
    email: "admin@globetrotter.io",
    role: "Admin",
    status: "Active",
    joinDate: "Jan 01, 2023",
    tripsCount: 25,
    spentTotal: 52000,
  },
];

export const sampleAdminStats: AdminStats = {
  totalUsers: 14820,
  activeTrips: 1840,
  totalRevenue: 284500,
  avgBudget: 2150,
  userGrowth: 24.8,
  topCities: [
    { name: "Paris, France", tripsCount: 3420, percentage: 34, color: "#3B82F6" },
    { name: "Tokyo, Japan", tripsCount: 2890, percentage: 28, color: "#8B5CF6" },
    { name: "Interlaken, Switzerland", tripsCount: 1920, percentage: 19, color: "#10B981" },
    { name: "New York City, USA", tripsCount: 1240, percentage: 12, color: "#F59E0B" },
    { name: "Bali, Indonesia", tripsCount: 710, percentage: 7, color: "#EC4899" },
  ],
  topActivities: [
    { name: "Tandem Paragliding", bookings: 1420, revenue: 269800 },
    { name: "Louvre After-Hours VIP", bookings: 2180, revenue: 185300 },
    { name: "Manta Point Scuba Diving", bookings: 1650, revenue: 181500 },
    { name: "Shinjuku Street Food Crawl", bookings: 1940, revenue: 145500 },
    { name: "Broadway Orchestra VIP", bookings: 890, revenue: 142400 },
  ],
  monthlyEngagement: [
    { month: "Aug", users: 8200, trips: 950 },
    { month: "Sep", users: 9600, trips: 1120 },
    { month: "Oct", users: 11400, trips: 1380 },
    { month: "Nov", users: 12800, trips: 1540 },
    { month: "Dec", users: 13900, trips: 1720 },
    { month: "Jan", users: 14820, trips: 1840 },
  ],
};
